export const PAY_ACCESS_TOKEN = 'PAY_ACCESS_TOKEN';
export const PAY_REFRESH_TOKEN = 'PAY_REFRESH_TOKEN';
export const BASE_URL = 'BASE_URL';
export const BARCODE_LABEL_TYPE = 'BARCODE_LABEL_TYPE';
export const PRODUCT_STATISTIC_SETTINGS = 'PRODUCT_STATISTIC_SETTINGS';
